### ISSUE TITLE
'MutatorVisitor' object has no attribute 'pn'

### ISSUE THREAD

**Issue by lv2020** [pmorvalho/MultIPAs#1]
Hi, thanks for the contribution! I run your code with "python3 prog_mutator.py -d inputs-demo -o mutated_programs -fw -v" and get:
```
Dealing with student  sum
Traceback (most recent call last):
  File "prog_mutator.py", line 847, in <module>
    gen_program_mutations(input_dir, output_dir)
  File "prog_mutator.py", line 813, in gen_program_mutations
    s_muts = instrument_file(p, output_dir+"/"+stu_id)
  File "prog_mutator.py", line 659, in instrument_file
    n_ast = v.visit(ast)
  File "prog_mutator.py", line 78, in visit
    return c_ast.NodeVisitor.visit(self, node)
  File "/home/liwei/miniconda3/envs/IPA/lib/python3.8/site-packages/pycparser/c_ast.py", line 158, in visit
    return visitor(node)
  File "prog_mutator.py", line 86, in visit_FileAST
    n_ext.append(self.visit(x))
  File "prog_mutator.py", line 78, in visit
    return c_ast.NodeVisitor.visit(self, node)
  File "/home/liwei/miniconda3/envs/IPA/lib/python3.8/site-packages/pycparser/c_ast.py", line 158, in visit
    return visitor(node)
  File "prog_mutator.py", line 207, in visit_FuncDef
    n_body_1 = self.visit(body)
  File "prog_mutator.py", line 78, in visit
    return c_ast.NodeVisitor.visit(self, node)
  File "/home/liwei/miniconda3/envs/IPA/lib/python3.8/site-packages/pycparser/c_ast.py", line 158, in visit
    return visitor(node)
  File "prog_mutator.py", line 246, in visit_Compound
    n_block_items.append(self.visit(x))
  File "prog_mutator.py", line 78, in visit
    return c_ast.NodeVisitor.visit(self, node)
  File "/home/liwei/miniconda3/envs/IPA/lib/python3.8/site-packages/pycparser/c_ast.py", line 158, in visit
    return visitor(node)
  File "/home/liwei/MultIPAs/helper.py", line 469, in visit_Return
    prv_pn = self.pn
AttributeError: 'MutatorVisitor' object has no attribute 'pn'
```

While I'm using the same environment as mentioned in README. And when I add a 'self.pn' under prog_mutator.py/MutatorVisitor, it works. Is it a correct fix? Thanks!

**Comment by pmorvalho** [comment]
Hello,

Thanks for the issue!

I made a few changes to the framework in August, added the ASTVisitor and forgot to call its constructor when the mutator is initialized, i.e. super().__init__(). The ASTVisitor is now the superclass of the MutatorVisitor. Now it is fixed.

Please, let me know if you find more problems.

Thank you for the warning!
